"""Build the homepage gallery manifest from images/.

Scans the `images/` folder for supported image files and writes
`data/gallery.js` as `window.SITE_GALLERY = [...]`.

AUTO-GENERATED output -- do not edit `data/gallery.js` by hand.
Just add/remove images in `images/` and re-run:

    python scripts/build-gallery-manifest.py

A GitHub Action (.github/workflows/gallery-manifest.yml) re-runs this
on every push that touches `images/` so github.io stays in sync with
zero manual list maintenance.
"""

import json
import urllib.parse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
IMAGES_DIR = ROOT / "images"
OUTPUT_JS = ROOT / "data" / "gallery.js"

SUPPORTED_EXTS = {".png", ".jpg", ".jpeg", ".gif", ".webp"}


def main():
    try:
        # Recursive like the workflow trigger (images/**) so nested
        # folders publish too; paths stay relative to images/.
        candidates = [p for p in IMAGES_DIR.rglob("*") if p.is_file()]
    except FileNotFoundError:
        candidates = []
    files = sorted(
        (p for p in candidates if p.suffix.lower() in SUPPORTED_EXTS),
        key=lambda p: p.relative_to(IMAGES_DIR).as_posix().lower(),
    )
    paths = [
        "images/" + "/".join(urllib.parse.quote(part, safe="") for part in p.relative_to(IMAGES_DIR).parts)
        for p in files
    ]

    lines = [
        "/**",
        " * MEOWKING - Homepage Gallery Manifest (AUTO-GENERATED)",
        " * -------------------------------------------------------------",
        " * Do NOT edit by hand. Generated by scripts/build-gallery-manifest.py",
        " * from the contents of images/. Add/remove images there and re-run",
        " * the script (or push -- the gallery-manifest workflow does it).",
        " */",
        "",
        "window.SITE_GALLERY = [",
    ]
    for path in paths:
        lines.append("  " + json.dumps(path) + ",")
    lines.append("];")
    lines.append("")

    OUTPUT_JS.write_text("\n".join(lines), encoding="utf-8")
    print(f"gallery manifest: {len(paths)} image(s) -> {OUTPUT_JS.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
